var transport = {
  types: [
    {
      name: "KTM 500 EXC 2800",
      class: "motorbike 1p 1d 2d 3d 4d 5d",
      image: "motorbike-1.jpeg",
      image1: "motorbike-2.jpeg",
      image2: "motorbike-3.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "1010",
      // value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["motorbike-1.jpeg", "motorbike-2.jpeg", "motorbike-3.jpeg"],
      people: 1,
      fuel: "3.7l/100km",
      reviews:["Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie."],
      approxFuelSpend: "$30",
      id: "transport1"
    },
    {
      name: "KTM This has more reviews 500 EXC 2800",
      class: "motorbike 1p 1d 2d 3d 4d 5d",
      image: "motorbike-2.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked", "checked"],
      unchecked: ["unchecked", "unchecked"],
      available: "Available",
      price: "1090",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["motorbike-2.jpeg", "motorbike-2.jpeg", "motorbike-3.jpeg"],
      people: 1,
      fuel: "3.7l/100km",
      reviews:["Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie."],
      approxFuelSpend: "$30",
      id: "transport2"
    },
    {
      name: "KTM 500 EXC 2800",
      class: "motorbike 1p 1d 2d 3d 4d 5d",
      image: "motorbike-3.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "109",
      // value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["motorbike-3.jpeg", "motorbike-2.jpeg", "motorbike-3.jpeg"],
      people: 1,
      fuel: "3.7l/100km",
      reviews:["Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie."],
      approxFuelSpend: "$30",
      id: "transport3"
    },
    {
      name: "KTM 500 EXC 2800",
      class: "motorbike 1p 1d 2d 3d 4d 5d",
      image: "motorbike-4.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "109",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["motorbike-4.jpeg", "motorbike-2.jpeg", "motorbike-3.jpeg"],
      people: 1,
      fuel: "3.7l/100km",
      reviews:["Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie."],
      approxFuelSpend: "$30",
      id: "transport4"
    },
    {
      name: "KTM 500 EXC 2800",
      class: "motorbike 1p 1d 2d 3d 4d 5d",
      image: "motorbike-5.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "109",
      // value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["motorbike-5.jpeg", "motorbike-2.jpeg", "motorbike-3.jpeg"],
      people: 1,
      fuel: "3.7l/100km",
      reviews:["Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie."],
      approxFuelSpend: "$30",
      id: "transport5"
    },
    {
      name: "KTM 500 EXC 2800",
      class: "motorbike 1p 1d 2d 3d 4d 5d",
      image: "motorbike-6.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "109",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["motorbike-6.jpeg", "motorbike-2.jpeg", "motorbike-3.jpeg"],
      people: 1,
      fuel: "3.7l/100km",
      reviews:["Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie."],
      approxFuelSpend: "$30",
      id: "transport6"
    },
    {
      name: "KTM 500 EXC 2800",
      class: "motorbike 1p 1d 2d 3d 4d 5d",
      image: "motorbike-7.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "10229",
      // value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["motorbike-7.jpeg", "motorbike-6.jpeg", "motorbike-3.jpeg"],
      people: 1,
      fuel: "3.7l/100km",
      reviews:["Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie."],
      approxFuelSpend: "$30",
      id: "transport7"
    },
    {
      name: "KTM 500 EXC 2800",
      class: "car 1p 2p 1p 1d 2d 3d 4d 5d 6d 7d 8d 9d 10d",
      image: "car-1.jpg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "28118",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["car-1.jpg", "car-2.png", "car-3.png"],
      people: "1-2",
      fuel: "8.5l/100km",
      reviews:["Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie."],
      approxFuelSpend: "$30",
      id: "transport8"
    },
    {
      name: "KTM 500 EXC 2800",
      class: "car 1p 2p 1p 1d 2d 3d 4d 5d 6d 7d 8d 9d 10d",
      image: "car-2.png",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["car-2.png", "car-2.png", "car-3.png"],
      people: "1-2",
      fuel: "8.5l/100km",
      reviews:["Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie."],
      approxFuelSpend: "$30",
      id: "transport9"
    },
    {
      name: "KTM 500 EXC 2800",
      class: "car 1p 2p 1p 1d 2d 3d 4d 5d 6d 7d 8d 9d 10d",
      image: "car-3.png",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["car-3.png", "car-2.png", "car-3.png"],
      people: "1-2",
      fuel: "8.5l/100km",
      reviews:["Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie."],
      approxFuelSpend: "$30",
      id: "transport10"
    },
    {
      name: "KTM 500 EXC 2800",
      class: "car 1p 2p 1p 1d 2d 3d 4d 5d 6d 7d 8d 9d 10d",
      image: "car-4.png",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["car-4.png", "car-2.png", "car-3.png"],
      people: "1-2",
      fuel: "8.5l/100km",
      reviews:["Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie."],
      approxFuelSpend: "$30",
      id: "transport11"
    },
    {
      name: "KTM 500 EXC 2800",
      class: "car 1p 2p 1p 1d 2d 3d 4d 5d 6d 7d 8d 9d 10d",
      image: "car-5.jpg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["car-5.jpg", "car-2.png", "car-3.png"],
      people: "1-2",
      fuel: "8.5l/100km",
      reviews:["Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie."],
      approxFuelSpend: "$30",
      id: "transport12"
    },
    {
      name: "KTM 500 EXC 2800",
      class: "largecar 1p 2p 3p 4p 5p 3d 4d 5d 6d 7d 8d 9d 10d",
      image: "large-car-1.jpg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["large-car-1.jpg", "large-car-2.jpg", "large-car-3.jpg"],
      people: "1-5",
      fuel: "9.7l/100km",
      reviews:["Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie."],
      approxFuelSpend: "$30",
      id: "transport13"
    },
    {
      name: "KTM 500 EXC 2800",
      class: "largecar 1p 2p 3p 4p 5p 3d 4d 5d 6d 7d 8d 9d 10d",
      image: "large-car-2.jpg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      // value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["large-car-2.jpg", "large-car-2.jpg", "large-car-3.jpg"],
      people: "1-5",
      fuel: "9.7l/100km",
      reviews:["Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie."],
      approxFuelSpend: "$30",
      id: "transport14"
    },
    {
      name: "KTM 500 EXC 2800",
      class: "largecar 1p 2p 3p 4p 5p 3d 4d 5d 6d 7d 8d 9d 10d",
      image: "large-car-3.jpg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["large-car-3.jpg", "large-car-2.jpg", "large-car-3.jpg"],
      people: "1-5",
      fuel: "9.7l/100km",
      reviews:["Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie."],
      approxFuelSpend: "$30",
      id: "transport15"
    },
    {
      name: "KTM 500 EXC 2800",
      class: "largecar 1p 2p 3p 4p 5p 3d 4d 5d 6d 7d 8d 9d 10d",
      image: "large-car-4.jpg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["large-car-4.jpg", "large-car-2.jpg", "large-car-3.jpg"],
      people: "1-5",
      fuel: "9.7l/100km",
      reviews:["Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie."],
      approxFuelSpend: "$30",
      id: "transport16"
    },
    {
      name: "KTM 500 EXC 2800",
      class: "largecar 1p 2p 3p 4p 5p 3d 4d 5d 6d 7d 8d 9d 10d",
      image: "large-car-5.jpg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["large-car-5.jpg", "large-car-2.jpg", "large-car-3.jpg"],
      people: "1-5",
      fuel: "9.7l/100km",
      reviews:["Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie."],
      approxFuelSpend: "$30",
      id: "transport17"
    },
    {
      name: "KTM 500 EXC 2800",
      class: "largecar 1p 2p 3p 4p 5p 3d 4d 5d 6d 7d 8d 9d 10d",
      image: "large-car-6.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["large-car-6.jpeg", "large-car-2.jpg", "large-car-3.jpg"],
      people: "1-5",
      fuel: "9.7l/100km",
      reviews:["Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie."],
      approxFuelSpend: "$30",
      id: "transport18"
    },
    {
      name: "KTM 500 EXC 2800",
      class: "motorhome 2p 3p 4p 5p 6p 2d 3d 4d 5d 6d 7d 8d 9d 10d 11d 12d 13d 14d 15d",
      image: "motor-van-1.jpg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["motor-van-1.jpg", "motor-van-3.jpg", "motor-van-4.jpg"],
      people: "2-6",
      reviews:["Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie."],
      approxFuelSpend: "$30",
      id: "transport19"

    },
    {
      name: "KTM 500 EXC 2800",
      class: "motorhome 2p 3p 4p 5p 6p 2d 3d 4d 5d 6d 7d 8d 9d 10d 11d 12d 13d 14d 15d",
      image: "motor-van-3.jpg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["motor-van-3.jpg", "motor-van-3.jpg", "motor-van-4.jpg"],
      people: "2-6",
      fuel: "17l/100km",
      reviews:["Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie."],
      approxFuelSpend: "$30",
      id: "transport20"
    },
    {
      name: "KTM 500 EXC 2800",
      class: "motorhome 2p 3p 4p 5p 6p 2d 3d 4d 5d 6d 7d 8d 9d 10d 11d 12d 13d 14d 15d",
      image: "motor-van-4.jpg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["motor-van-4.jpg", "motor-van-3.jpg", "motor-van-4.jpg"],
      people: "2-6",
      fuel: "17l/100km",
      reviews:["Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie."],
      approxFuelSpend: "$30",
      id: "transport21"
    },
    {
      name: "KTM 500 EXC 2800",
      class: "motorhome 2p 3p 4p 5p 6p 2d 3d 4d 5d 6d 7d 8d 9d 10d 11d 12d 13d 14d 15d",
      image: "motor-van-5.jpg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["motor-van-5.jpg", "motor-van-3.jpg", "motor-van-4.jpg"],
      people: "2-6",
      fuel: "17l/100km",
      reviews:["Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie."],
      approxFuelSpend: "$30",
      id: "transport22"
    },
    {
      name: "KTM 500 EXC 2800",
      class: "motorhome 2p 3p 4p 5p 6p 2d 3d 4d 5d 6d 7d 8d 9d 10d 11d 12d 13d 14d 15d",
      image: "motor-van-3.jpg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked", "checked"],
      unchecked: ["unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["motor-van-3.jpg", "motor-van-3.jpg", "motor-van-4.jpg"],
      people: "2-6",
      fuel: "17l/100km",
      reviews:["Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie."],
      approxFuelSpend: "$30",
      id: "transport23"
    },
  ]
};

// ======================================== ACCOMMODATION ============================================================

var accommodation = {
  types: [
    {
      name: "Hotel Victoria",
      class: "hotel 1p 2p 1d 2d 3d 4d 5d",
      image: "hotel-1.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      // value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hotel-1.jpeg", "hotel-2.jpeg", "hotel-3.jpeg"],
      people: "1-2",
      mealsImage: ["img/breakfast.jpeg", "img/lunch.jpeg"],
      reviews:["Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie."]
    },
    {
      name: "Hotel Victoria",
      class: "hotel 1p 2p 1d 2d 3d 4d 5d",
      image: "hotel-2.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hotel-2.jpeg", "hotel-2.jpeg", "hotel-3.jpeg"],
      people: "1-2",
      mealsImage: ["img/breakfast.jpeg", "img/lunch.jpeg"],
      reviews:["Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie."]
    },
    {
      name: "Hotel Victoria",
      class: "hotel 1p 2p 1d 2d 3d 4d 5d",
      image: "hotel-3.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      // value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hotel-3.jpeg", "hotel-2.jpeg", "hotel-3.jpeg"],
      people: "1-2",
      mealsImage: ["img/breakfast.jpeg", "img/lunch.jpeg"],
      reviews:["Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie."]
    },
    {
      name: "Hotel Victoria",
      class: "hotel 1p 2p 1d 2d 3d 4d 5d",
      image: "hotel-4.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hotel-4.jpeg", "hotel-2.jpeg", "hotel-3.jpeg"],
      people: "1-2",
      mealsImage: ["img/breakfast.jpeg", "img/lunch.jpeg"],
      reviews:["Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie."]
    },
    {
      name: "Hotel Victoria",
      class: "hotel 1p 2p 1d 2d 3d 4d 5d",
      image: "hotel-4.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hotel-4.jpeg", "hotel-2.jpeg", "hotel-3.jpeg"],
      people: "1-2",
      mealsImage: ["img/breakfast.jpeg", "img/lunch.jpeg"],
      reviews:["Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie."]
    },
    {
      name: "Hostel Victoria",
      class: "hostel 1p 1d 2d 3d 4d 5d 6d 7d 8d 9d 10d",
      image: "hostel-1.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hostel-1.jpeg", "hostel-2.jpg", "hostel-1.jpeg"],
      people: 1,
      mealsImage: ["img/breakfast.jpeg", "img/lunch.jpeg"],
      reviews:["Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie."]
    },
    {
      name: "Hostel Victoria",
      class: "hostel 1p 1d 2d 3d 4d 5d 6d 7d 8d 9d 10d",
      image: "hostel-2.jpg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hostel-2.jpeg", "hostel-2.jpg", "hostel-1.jpeg"],
      people: 1,
      mealsImage: ["img/breakfast.jpeg", "img/lunch.jpeg"],
      reviews:["Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie."]
    },
    {
      name: "Motel Victoria",
      class: "motel 2p 3p 4p 3d 4d 5d 6d 7d 8d 9d 10d",
      image: "motel-1.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["motel-1.jpeg", "motel-2.jpeg", "motel-1.jpeg"],
      people: "2-4",
      mealsImage: ["img/breakfast.jpeg", "img/lunch.jpeg"],
      reviews:["Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie."]
    },
    {
      name: "Motel Victoria",
      class: "motel 2p 3p 4p 3d 4d 5d 6d 7d 8d 9d 10d",
      image: "motel-2.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["motel-2.jpeg", "motel-2.jpeg", "motel-1.jpeg"],
      people: "2-4",
      mealsImage: ["img/breakfast.jpeg", "img/lunch.jpeg"],
      reviews:["Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie."]
    },
    {
      name: "House Victoria",
      class: "house 1p 2p 3p 4p 2d 3d 4d 5d 6d 7d 8d 9d 10d 11d 12d 13d 14d 15d",
      image: "house-1.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      // value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["house-1.jpeg", "house-2.jpeg", "house-3.jpeg"],
      people: "1-4",
      mealsImage: ["img/breakfast.jpeg", "img/lunch.jpeg"],
      reviews:["Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie."]
    },
    {
      name: "House Victoria",
      class: "house 1p 2p 3p 4p 2d 3d 4d 5d 6d 7d 8d 9d 10d 11d 12d 13d 14d 15d",
      image: "house-2.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["house-2.jpeg", "house-2.jpeg", "house-3.jpeg"],
      people: "1-4",
      mealsImage: ["img/breakfast.jpeg", "img/lunch.jpeg"],
      reviews:["Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie."]
    },
    {
      name: "House Victoria",
      class: "house 1p 2p 3p 4p 2d 3d 4d 5d 6d 7d 8d 9d 10d 11d 12d 13d 14d 15d",
      image: "house-3.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["house-3.jpeg", "house-2.jpeg", "house-3.jpeg"],
      people: "1-4",
      mealsImage: ["img/breakfast.jpeg", "img/lunch.jpeg"],
      reviews:["Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie."]
    },
    {
      name: "House Victoria",
      class: "house 1p 2p 3p 4p 2d 3d 4d 5d 6d 7d 8d 9d 10d 11d 12d 13d 14d 15d",
      image: "house-4.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["house-4.jpeg", "house-2.jpeg", "house-3.jpeg"],
      people: "1-4",
      mealsImage: ["img/breakfast.jpeg", "img/lunch.jpeg"],
      reviews:["Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie."]
    },
    {
      name: "House Victoria",
      class: "house 1p 2p 3p 4p 2d 3d 4d 5d 6d 7d 8d 9d 10d 11d 12d 13d 14d 15d",
      image: "house-6.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["house-6.jpeg", "house-2.jpeg", "house-3.jpeg"],
      people: "1-4",
      mealsImage: ["img/breakfast.jpeg", "img/lunch.jpeg"],
      reviews:["Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie.", "Kia ora.. Spit the dummy, this crook cuzzie is as pearler as a heaps good housie."]
    },
  ]
};


// JUST BOOKED DATA

justBookedData = {
  types: [
    { 
      img:"img/house-1.jpeg",
      nameTop : "TREEEHOUSE • AUCKLAND", 
      title : "Romantic Bush Chalet - Kauri Chalet",
      price: "$175 NZD per night • Free cancellation",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      superHostTitle: "373 • Superhost"
    },
    { 
      nameTop : "TREEEHOUSE • AUCKLAND", 
      title : "Romantic Bush Chalet - Kauri Chalet",
      price: "$175 NZD per night • Free cancellation",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      img:"img/house-2.jpeg",
      superHostTitle: "373 • Superhost"
      
    },
    { 
      nameTop : "TREEEHOUSE • AUCKLAND", 
      title : "Romantic Bush Chalet - Kauri Chalet",
      price: "$175 NZD per night • Free cancellation",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      img:"img/house-3.jpeg",
      superHostTitle: "373 • Superhost"
    },
    { 
      nameTop : "TREEEHOUSE • AUCKLAND", 
      title : "Romantic Bush Chalet - Kauri Chalet",
      price: "$175 NZD per night • Free cancellation",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      img:"img/house-4.jpeg",
      superHostTitle: "373 • Superhost"
    },
  ]
};

