var transport = {
  types: [
    {
      name: "KTM 500 EXC 2800",
      class: "motorbike 1p 1d 2d 3d 4d 5d",
      image: "motorbike-1.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "109",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hammer.jpg", "hammer.jpg", "hammer.jpg"]
    },
    {
      name: "KTM 500 EXC 2800",
      class: "motorbike 1p 1d 2d 3d 4d 5d",
      image: "motorbike-2.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "109",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hammer.jpg", "hammer.jpg", "hammer.jpg"]
    },
    {
      name: "KTM 500 EXC 2800",
      class: "motorbike 1p 1d 2d 3d 4d 5d",
      image: "motorbike-3.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "109",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hammer.jpg", "hammer.jpg", "hammer.jpg"]
    },
    {
      name: "KTM 500 EXC 2800",
      class: "motorbike 1p 1d 2d 3d 4d 5d",
      image: "motorbike-4.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "109",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hammer.jpg", "hammer.jpg", "hammer.jpg"]
    },
    {
      name: "KTM 500 EXC 2800",
      class: "motorbike 1p 1d 2d 3d 4d 5d",
      image: "motorbike-5.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "109",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hammer.jpg", "hammer.jpg", "hammer.jpg"]
    },
    {
      name: "KTM 500 EXC 2800",
      class: "motorbike 1p 1d 2d 3d 4d 5d",
      image: "motorbike-6.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "109",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hammer.jpg", "hammer.jpg", "hammer.jpg"]
    },
    {
      name: "KTM 500 EXC 2800",
      class: "motorbike 1p 1d 2d 3d 4d 5d",
      image: "motorbike-7.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "109",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hammer.jpg", "hammer.jpg", "hammer.jpg"]
    },
    {
      name: "KTM 500 EXC 2800",
      class: "car 1p 2p 1p 1d 2d 3d 4d 5d 6d 7d 8d 9d 10d",
      image: "car-1.jpg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hammer.jpg", "hammer.jpg", "hammer.jpg"]
    },
    {
      name: "KTM 500 EXC 2800",
      class: "car 1p 2p 1p 1d 2d 3d 4d 5d 6d 7d 8d 9d 10d",
      image: "car-2.png",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hammer.jpg", "hammer.jpg", "hammer.jpg"]
    },
    {
      name: "KTM 500 EXC 2800",
      class: "car 1p 2p 1p 1d 2d 3d 4d 5d 6d 7d 8d 9d 10d",
      image: "car-3.png",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hammer.jpg", "hammer.jpg", "hammer.jpg"]
    },
    {
      name: "KTM 500 EXC 2800",
      class: "car 1p 2p 1p 1d 2d 3d 4d 5d 6d 7d 8d 9d 10d",
      image: "car-4.png",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hammer.jpg", "hammer.jpg", "hammer.jpg"]
    },
    {
      name: "KTM 500 EXC 2800",
      class: "car 1p 2p 1p 1d 2d 3d 4d 5d 6d 7d 8d 9d 10d",
      image: "car-5.jpg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hammer.jpg", "hammer.jpg", "hammer.jpg"]
    },
    {
      name: "KTM 500 EXC 2800",
      class: "largecar 1p 2p 3p 4p 5p 3d 4d 5d 6d 7d 8d 9d 10d",
      image: "large-car-1.jpg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hammer.jpg", "hammer.jpg", "hammer.jpg"]
    },
    {
      name: "KTM 500 EXC 2800",
      class: "largecar 1p 2p 3p 4p 5p 3d 4d 5d 6d 7d 8d 9d 10d",
      image: "large-car-2.jpg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hammer.jpg", "hammer.jpg", "hammer.jpg"]
    },
    {
      name: "KTM 500 EXC 2800",
      class: "largecar 1p 2p 3p 4p 5p 3d 4d 5d 6d 7d 8d 9d 10d",
      image: "large-car-3.jpg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hammer.jpg", "hammer.jpg", "hammer.jpg"]
    },
    {
      name: "KTM 500 EXC 2800",
      class: "largecar 1p 2p 3p 4p 5p 3d 4d 5d 6d 7d 8d 9d 10d",
      image: "large-car-4.jpg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hammer.jpg", "hammer.jpg", "hammer.jpg"]
    },
    {
      name: "KTM 500 EXC 2800",
      class: "largecar 1p 2p 3p 4p 5p 3d 4d 5d 6d 7d 8d 9d 10d",
      image: "large-car-5.jpg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hammer.jpg", "hammer.jpg", "hammer.jpg"]
    },
    {
      name: "KTM 500 EXC 2800",
      class: "largecar 1p 2p 3p 4p 5p 3d 4d 5d 6d 7d 8d 9d 10d",
      image: "large-car-6.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hammer.jpg", "hammer.jpg", "hammer.jpg"]
    },
    {
      name: "KTM 500 EXC 2800",
      class: "motorhome 2p 3p 4p 5p 6p 2d 3d 4d 5d 6d 7d 8d 9d 10d 11d 12d 13d 14d 15d",
      image: "motor-van-1.jpg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hammer.jpg", "hammer.jpg", "hammer.jpg"]
    },
    {
      name: "KTM 500 EXC 2800",
      class: "motorhome 2p 3p 4p 5p 6p 2d 3d 4d 5d 6d 7d 8d 9d 10d 11d 12d 13d 14d 15d",
      image: "motor-van-3.jpg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hammer.jpg", "hammer.jpg", "hammer.jpg"]
    },
    {
      name: "KTM 500 EXC 2800",
      class: "motorhome 2p 3p 4p 5p 6p 2d 3d 4d 5d 6d 7d 8d 9d 10d 11d 12d 13d 14d 15d",
      image: "motor-van-4.jpg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hammer.jpg", "hammer.jpg", "hammer.jpg"]
    },
    {
      name: "KTM 500 EXC 2800",
      class: "motorhome 2p 3p 4p 5p 6p 2d 3d 4d 5d 6d 7d 8d 9d 10d 11d 12d 13d 14d 15d",
      image: "motor-van-5.jpg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hammer.jpg", "hammer.jpg", "hammer.jpg"]
    },
    {
      name: "KTM 500 EXC 2800",
      class: "motorhome 2p 3p 4p 5p 6p 2d 3d 4d 5d 6d 7d 8d 9d 10d 11d 12d 13d 14d 15d",
      image: "motor-van-3.jpg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked", "checked"],
      unchecked: ["unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hammer.jpg", "hammer.jpg", "hammer.jpg"]
    },
  ]
};

// ======================================== ACCOMMODATION ============================================================

var accommodation = {
  types: [
    {
      name: "Hotel Victoria",
      class: "hotel 1p 2p 1d 2d 3d 4d 5d",
      image: "hotel-1.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hammer.jpg", "hammer.jpg", "hammer.jpg"]
    },
    {
      name: "Hotel Victoria",
      class: "hotel 1p 2p 1d 2d 3d 4d 5d",
      image: "hotel-2.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hammer.jpg", "hammer.jpg", "hammer.jpg"]
    },
    {
      name: "Hotel Victoria",
      class: "hotel 1p 2p 1d 2d 3d 4d 5d",
      image: "hotel-3.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hammer.jpg", "hammer.jpg", "hammer.jpg"]
    },
    {
      name: "Hotel Victoria",
      class: "hotel 1p 2p 1d 2d 3d 4d 5d",
      image: "hotel-4.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hammer.jpg", "hammer.jpg", "hammer.jpg"]
    },
    {
      name: "Hotel Victoria",
      class: "hotel 1p 2p 1d 2d 3d 4d 5d",
      image: "hotel-4.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hammer.jpg", "hammer.jpg", "hammer.jpg"]
    },
    {
      name: "Hostel Victoria",
      class: "hostel 1p 1d 2d 3d 4d 5d 6d 7d 8d 9d 10d",
      image: "hostel-1.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hammer.jpg", "hammer.jpg", "hammer.jpg"]
    },
    {
      name: "Hostel Victoria",
      class: "hostel 1p 1d 2d 3d 4d 5d 6d 7d 8d 9d 10d",
      image: "hostel-2.jpg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hammer.jpg", "hammer.jpg", "hammer.jpg"]
    },
    {
      name: "Motel Victoria",
      class: "motel 2p 3p 4p 3d 4d 5d 6d 7d 8d 9d 10d",
      image: "motel-1.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hammer.jpg", "hammer.jpg", "hammer.jpg"]
    },
    {
      name: "Motel Victoria",
      class: "motel 2p 3p 4p 3d 4d 5d 6d 7d 8d 9d 10d",
      image: "motel-2.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hammer.jpg", "hammer.jpg", "hammer.jpg"]
    },
    {
      name: "House Victoria",
      class: "house 1p 2p 3p 4p 2d 3d 4d 5d 6d 7d 8d 9d 10d 11d 12d 13d 14d 15d",
      image: "house-1.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hammer.jpg", "hammer.jpg", "hammer.jpg"]
    },
    {
      name: "House Victoria",
      class: "house 1p 2p 3p 4p 2d 3d 4d 5d 6d 7d 8d 9d 10d 11d 12d 13d 14d 15d",
      image: "house-2.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hammer.jpg", "hammer.jpg", "hammer.jpg"]
    },
    {
      name: "House Victoria",
      class: "house 1p 2p 3p 4p 2d 3d 4d 5d 6d 7d 8d 9d 10d 11d 12d 13d 14d 15d",
      image: "house-3.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hammer.jpg", "hammer.jpg", "hammer.jpg"]
    },
    {
      name: "House Victoria",
      class: "house 1p 2p 3p 4p 2d 3d 4d 5d 6d 7d 8d 9d 10d 11d 12d 13d 14d 15d",
      image: "house-4.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hammer.jpg", "hammer.jpg", "hammer.jpg"]
    },
    {
      name: "House Victoria",
      class: "house 1p 2p 3p 4p 2d 3d 4d 5d 6d 7d 8d 9d 10d 11d 12d 13d 14d 15d",
      image: "house-6.jpeg",
      description: "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway",
      checked: ["checked", "checked"],
      unchecked: ["unchecked", "unchecked", "unchecked"],
      available: "Available",
      price: "288",
      value: "$99 until Dec 2018",
      reviews: 8,
      reviewDescription: ["Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway", "Wan Chai and Causeway Bay | 1.8 km from downtown | Near the subway"],
      images: ["hammer.jpg", "hammer.jpg", "hammer.jpg"]
    },
  ]
};




